[tool.poetry]
name = "multiplication-game"
version = "0.1.0"
description = ""
authors = ["hd <hillier_dani@yahoo.fr>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

